### PR TITLE
Restore possibility to build with Java 8

### PR DESCRIPTION
**Pull request by fridrich**
Replace the few "var" occurrences that are not compatible with java 8. After this, the code should be again completely buildable with any JDK 1.8+

### CODE REVIEW

**Comment by mizdebsk** [comment]
Thank you for the pull request and sorry for delay in reviewing it.
Can you explain why building and running XMvn with Java 8 matters for you?
I was considering the opposite change - start using newer Java features.

**Comment by fridrich** [comment]
Ok, our approach is that we try to keep the stuff runnable as much as possible with java 8. We don't use the same approach with toolchains in maven-local-jdk8 or what is it called. That is why if it is possible, I try to keep the xmvn at least runnable with java 8. Like that each package's spec file can tell the build which span of java versions can build it and it will be used. We do something like BuildRequires: java-devel >= N and then BuildConflicts: java-devel >= M and it will build with any java version we have that is in the interval [N,M). Since I saw that one could achieve the Java 8 compatibility quite cheap, just some vars change to the actual types and one one revert of java 9+ feature and it was ok, so I tried to submit. Free for you to accept or reject, although java 8 compatibility would be making my life easier, but my life is nothing compared to eternity ;)

**Comment by mizdebsk** [comment]
I see. I'm inclined to accept this change.
Do you have any estimation how long Java 8 compatibility will be needed?

**Comment by fridrich** [comment]
OK, you people on your web-site give it Nov. 2026 as EOL. I think that we will do the same. Currently, I was trying to diminish its footprint in SUSE distributions, but things are not as easy as that.
Then I gave it a thought and told myself that infrastructure packages like xmvn that are used only for building don't really need badly to have the newest of the newest features, since some performance improvements are not as important. And the "var" changes, although they make programming easier and faster, can be always done by tracking down a real type manually instead of letting compiler to do it :)

**Comment by fridrich** [comment]
Dięki :P

**Comment by fridrich** [comment]
Now, it is true that the unix domain sockets are convenient and it is much better to not pass over the tcp/ip stack. One solution would be to abstract that api into one class and then create a multi-release jar that would have the version/16/ with the modern solutions ?

**Comment by mizdebsk** [comment]
Optional functionality requiring new Java features can be implemented separately and called from XMvn.

(What I specifically have in mind right now is support for [mock pm_request plugin](https://fedoraproject.org/wiki/Projects/Mock/Plugin/PMRequest) (MockAgent class in XMvn), that allows XMvn to communicate with DNF package manager to request installation of missing artifacts on-demand. XMvn is typically ran in a chroot, while DNF is outsides of chroot. Communication between XMvn and DNF is done using Unix domain socket.)

**Comment by fridrich** [comment]
Any possibility to release something like 4.0.1 or somesuch?

**Pull request merged**
